"""Offer elevator is now a bool

Revision ID: fe4e478b3610
Revises: ec25c2dec8b7
Create Date: 2025-05-06 21:58:49.167383

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fe4e478b3610"
down_revision: Union[str, None] = "ec25c2dec8b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE offer
        SET elevator = CASE
            WHEN LOWER(SUBSTRING(elevator, 1, 1)) = 't' THEN TRUE
            ELSE FALSE
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE offer
        SET elevator = CASE
            WHEN elevator = 'true' THEN TRUE
            ELSE FALSE
        END
        """
    )
    # ### end Alembic commands ###
